# Generated by Django 5.2.6 on 2025-10-07 06:56

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.CreateModel(
            name="Index",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("accordion", 8),
                            ("alert", 20),
                            ("document", 21),
                            ("image", 25),
                            ("list", 34),
                            ("quote", 35),
                            ("text", 36),
                            ("tabs", 55),
                            ("timeline", 63),
                            ("video", 64),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accordion name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                                    "help_text": "Accordion style",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "check-circle2",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Wether to show or hide item content",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Item content", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 2),
                                        ("is_expanded", 3),
                                        ("title", 4),
                                        ("content", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"help_text": "Accordion items", "required": True},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("style", 1), ("items", 7)]],
                                {"help_text": "Accordion"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "alert-triangle",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if alert is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("soft", "Soft"),
                                        ("outline", "Outline"),
                                        ("dash", "Dash"),
                                    ],
                                    "help_text": "Alert style",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Alert level",
                                },
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "code",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Alert message",
                                    "required": True,
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Action label",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Action internal link",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Action external link",
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Action button color",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 2),
                                        ("label", 14),
                                        ("page", 15),
                                        ("url", 16),
                                        ("color", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Alert actions", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 9),
                                        ("is_vertical", 10),
                                        ("style", 11),
                                        ("level", 12),
                                        ("message", 13),
                                        ("actions", 19),
                                    ]
                                ],
                                {"help_text": "Alert"},
                            ),
                            21: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                            22: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image caption",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image attribution",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 22), ("caption", 23), ("attribution", 24)]],
                                {"help_text": "Image"},
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "List title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            27: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Item image"},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item description",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Item internal link", "required": False},
                            ),
                            30: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Item external link", "required": False},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Actions", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 27),
                                        ("title", 4),
                                        ("description", 28),
                                        ("page", 29),
                                        ("url", 30),
                                        ("actions", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.ListBlock",
                                (32,),
                                {"help_text": "List items", "required": True},
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 26), ("items", 33)]],
                                {"help_text": "List"},
                            ),
                            35: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            36: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Text"},
                            ),
                            37: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tab name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            38: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab buttons position is reversed",
                                    "required": False,
                                },
                            ),
                            39: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("border", "Border"),
                                        ("box", "Box"),
                                        ("lift", "Lift"),
                                    ],
                                    "help_text": "Tab style",
                                },
                            ),
                            40: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab is selected",
                                    "required": False,
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 9),
                                        ("is_vertical", 10),
                                        ("style", 11),
                                        ("level", 12),
                                        ("message", 13),
                                        ("actions", 19),
                                    ]
                                ],
                                {"help_text": "Alert", "required": True},
                            ),
                            42: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide which programming language is used",
                                    "required": False,
                                },
                            ),
                            43: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide copy buttons",
                                    "required": False,
                                },
                            ),
                            44: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide window buttons",
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Untitled",
                                    "help_text": "File name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            46: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("auto", "Auto"),
                                        ("bash", "Bash"),
                                        ("c", "C"),
                                        ("cpp", "C++"),
                                        ("csharp", "C#"),
                                        ("css", "CSS"),
                                        ("dart", "Dart"),
                                        ("dockerfile", "Dockerfile"),
                                        ("go", "Go"),
                                        ("html", "HTML"),
                                        ("java", "Java"),
                                        ("javascript", "JavaScript"),
                                        ("json", "JSON"),
                                        ("kotlin", "Kotlin"),
                                        ("lua", "Lua"),
                                        ("markdown", "Markdown"),
                                        ("php", "PHP"),
                                        ("python", "Python"),
                                        ("ruby", "Ruby"),
                                        ("rust", "Rust"),
                                        ("scss", "SCSS"),
                                        ("shell", "Shell"),
                                        ("sql", "SQL"),
                                        ("swift", "Swift"),
                                        ("typescript", "TypeScript"),
                                        ("xml", "XML"),
                                        ("yaml", "YAML"),
                                        ("plaintext", "Plain text"),
                                    ],
                                    "help_text": "Programming language",
                                },
                            ),
                            47: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code content", "required": True},
                            ),
                            48: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("show_language", 42),
                                        ("show_copy_btn", 43),
                                        ("show_window_btns", 44),
                                        ("file_name", 45),
                                        ("language", 46),
                                        ("code", 47),
                                    ]
                                ],
                                {"help_text": "Code", "required": True},
                            ),
                            49: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 22), ("caption", 23), ("attribution", 24)]],
                                {"help_text": "Image", "required": True},
                            ),
                            50: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": True},
                            ),
                            51: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich text", "required": True},
                            ),
                            52: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("alert", 41),
                                        ("code", 48),
                                        ("image", 49),
                                        ("video", 50),
                                        ("text", 51),
                                    ]
                                ],
                                {"help_text": "Tab Content", "required": True},
                            ),
                            53: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("is_selected", 40), ("content", 52)]],
                                {},
                            ),
                            54: (
                                "wagtail.blocks.ListBlock",
                                (53,),
                                {"help_text": "Tab items", "required": True},
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 37),
                                        ("is_reversed", 38),
                                        ("style", 39),
                                        ("items", 54),
                                    ]
                                ],
                                {"help_text": "Tabs"},
                            ),
                            56: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is compact",
                                    "required": False,
                                },
                            ),
                            57: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            58: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if dates should snap to icons",
                                    "required": False,
                                },
                            ),
                            59: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Item date", "required": True},
                            ),
                            60: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item content",
                                    "max_length": 128,
                                    "required": True,
                                },
                            ),
                            61: (
                                "wagtail.blocks.StructBlock",
                                [[("date", 59), ("icon", 2), ("content", 60)]],
                                {},
                            ),
                            62: (
                                "wagtail.blocks.ListBlock",
                                (61,),
                                {"help_text": "Timeline items", "required": True},
                            ),
                            63: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("is_compact", 56),
                                        ("is_vertical", 57),
                                        ("snap_to_icon", 58),
                                        ("items", 62),
                                    ]
                                ],
                                {"help_text": "Timeline"},
                            ),
                            64: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                        },
                        help_text="Page content",
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="SubIndex",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Page description",
                        max_length=256,
                        verbose_name="description",
                    ),
                ),
                (
                    "content",
                    wagtail.fields.StreamField(
                        [
                            ("accordion", 8),
                            ("alert", 20),
                            ("document", 21),
                            ("image", 25),
                            ("list", 34),
                            ("quote", 35),
                            ("text", 36),
                            ("tabs", 55),
                            ("timeline", 63),
                            ("video", 64),
                        ],
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Accordion name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("plus", "Plus"), ("arrow", "Arrow")],
                                    "help_text": "Accordion style",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "check-circle2",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Wether to show or hide item content",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            5: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Item content", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 2),
                                        ("is_expanded", 3),
                                        ("title", 4),
                                        ("content", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {"help_text": "Accordion items", "required": True},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("name", 0), ("style", 1), ("items", 7)]],
                                {"help_text": "Accordion"},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "alert-triangle",
                                    "help_text": "Icon name (lucide icons)",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            10: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if alert is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("soft", "Soft"),
                                        ("outline", "Outline"),
                                        ("dash", "Dash"),
                                    ],
                                    "help_text": "Alert style",
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("info", "Info"),
                                        ("success", "Success"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Alert level",
                                },
                            ),
                            13: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "document-link",
                                        "code",
                                        "superscript",
                                        "subscript",
                                        "strikethrough",
                                    ],
                                    "help_text": "Alert message",
                                    "required": True,
                                },
                            ),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Action label",
                                    "max_length": 32,
                                    "required": False,
                                },
                            ),
                            15: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Action internal link",
                                    "required": False,
                                },
                            ),
                            16: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Action external link",
                                    "required": False,
                                },
                            ),
                            17: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("accent", "Accent"),
                                        ("success", "Success"),
                                        ("info", "Info"),
                                        ("warning", "Warning"),
                                        ("error", "Error"),
                                    ],
                                    "help_text": "Action button color",
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 2),
                                        ("label", 14),
                                        ("page", 15),
                                        ("url", 16),
                                        ("color", 17),
                                    ]
                                ],
                                {},
                            ),
                            19: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Alert actions", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 9),
                                        ("is_vertical", 10),
                                        ("style", 11),
                                        ("level", 12),
                                        ("message", 13),
                                        ("actions", 19),
                                    ]
                                ],
                                {"help_text": "Alert"},
                            ),
                            21: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {"help_text": "Document"},
                            ),
                            22: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Image"},
                            ),
                            23: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image caption",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            24: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Image attribution",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            25: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 22), ("caption", 23), ("attribution", 24)]],
                                {"help_text": "Image"},
                            ),
                            26: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "List title",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            27: (
                                "wagtail.images.blocks.ImageBlock",
                                [],
                                {"help_text": "Item image"},
                            ),
                            28: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item description",
                                    "max_length": 128,
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"help_text": "Item internal link", "required": False},
                            ),
                            30: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {"help_text": "Item external link", "required": False},
                            ),
                            31: (
                                "wagtail.blocks.ListBlock",
                                (18,),
                                {"help_text": "Actions", "required": False},
                            ),
                            32: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 27),
                                        ("title", 4),
                                        ("description", 28),
                                        ("page", 29),
                                        ("url", 30),
                                        ("actions", 31),
                                    ]
                                ],
                                {},
                            ),
                            33: (
                                "wagtail.blocks.ListBlock",
                                (32,),
                                {"help_text": "List items", "required": True},
                            ),
                            34: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 26), ("items", 33)]],
                                {"help_text": "List"},
                            ),
                            35: (
                                "wagtail.blocks.BlockQuoteBlock",
                                (),
                                {"help_text": "Quote"},
                            ),
                            36: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Text"},
                            ),
                            37: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Tab name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            38: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab buttons position is reversed",
                                    "required": False,
                                },
                            ),
                            39: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("border", "Border"),
                                        ("box", "Box"),
                                        ("lift", "Lift"),
                                    ],
                                    "help_text": "Tab style",
                                },
                            ),
                            40: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if tab is selected",
                                    "required": False,
                                },
                            ),
                            41: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 9),
                                        ("is_vertical", 10),
                                        ("style", 11),
                                        ("level", 12),
                                        ("message", 13),
                                        ("actions", 19),
                                    ]
                                ],
                                {"help_text": "Alert", "required": True},
                            ),
                            42: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide which programming language is used",
                                    "required": False,
                                },
                            ),
                            43: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide copy buttons",
                                    "required": False,
                                },
                            ),
                            44: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "Wether to show or hide window buttons",
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "Untitled",
                                    "help_text": "File name",
                                    "max_length": 64,
                                    "required": True,
                                },
                            ),
                            46: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("auto", "Auto"),
                                        ("bash", "Bash"),
                                        ("c", "C"),
                                        ("cpp", "C++"),
                                        ("csharp", "C#"),
                                        ("css", "CSS"),
                                        ("dart", "Dart"),
                                        ("dockerfile", "Dockerfile"),
                                        ("go", "Go"),
                                        ("html", "HTML"),
                                        ("java", "Java"),
                                        ("javascript", "JavaScript"),
                                        ("json", "JSON"),
                                        ("kotlin", "Kotlin"),
                                        ("lua", "Lua"),
                                        ("markdown", "Markdown"),
                                        ("php", "PHP"),
                                        ("python", "Python"),
                                        ("ruby", "Ruby"),
                                        ("rust", "Rust"),
                                        ("scss", "SCSS"),
                                        ("shell", "Shell"),
                                        ("sql", "SQL"),
                                        ("swift", "Swift"),
                                        ("typescript", "TypeScript"),
                                        ("xml", "XML"),
                                        ("yaml", "YAML"),
                                        ("plaintext", "Plain text"),
                                    ],
                                    "help_text": "Programming language",
                                },
                            ),
                            47: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Code content", "required": True},
                            ),
                            48: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("show_language", 42),
                                        ("show_copy_btn", 43),
                                        ("show_window_btns", 44),
                                        ("file_name", 45),
                                        ("language", 46),
                                        ("code", 47),
                                    ]
                                ],
                                {"help_text": "Code", "required": True},
                            ),
                            49: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 22), ("caption", 23), ("attribution", 24)]],
                                {"help_text": "Image", "required": True},
                            ),
                            50: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video", "required": True},
                            ),
                            51: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Rich text", "required": True},
                            ),
                            52: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("alert", 41),
                                        ("code", 48),
                                        ("image", 49),
                                        ("video", 50),
                                        ("text", 51),
                                    ]
                                ],
                                {"help_text": "Tab Content", "required": True},
                            ),
                            53: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 4), ("is_selected", 40), ("content", 52)]],
                                {},
                            ),
                            54: (
                                "wagtail.blocks.ListBlock",
                                (53,),
                                {"help_text": "Tab items", "required": True},
                            ),
                            55: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("name", 37),
                                        ("is_reversed", 38),
                                        ("style", 39),
                                        ("items", 54),
                                    ]
                                ],
                                {"help_text": "Tabs"},
                            ),
                            56: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is compact",
                                    "required": False,
                                },
                            ),
                            57: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if timeline is vertical or horizontal (default)",
                                    "required": False,
                                },
                            ),
                            58: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Designates if dates should snap to icons",
                                    "required": False,
                                },
                            ),
                            59: (
                                "wagtail.blocks.DateBlock",
                                (),
                                {"help_text": "Item date", "required": True},
                            ),
                            60: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Item content",
                                    "max_length": 128,
                                    "required": True,
                                },
                            ),
                            61: (
                                "wagtail.blocks.StructBlock",
                                [[("date", 59), ("icon", 2), ("content", 60)]],
                                {},
                            ),
                            62: (
                                "wagtail.blocks.ListBlock",
                                (61,),
                                {"help_text": "Timeline items", "required": True},
                            ),
                            63: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("is_compact", 56),
                                        ("is_vertical", 57),
                                        ("snap_to_icon", 58),
                                        ("items", 62),
                                    ]
                                ],
                                {"help_text": "Timeline"},
                            ),
                            64: (
                                "wagtail.embeds.blocks.EmbedBlock",
                                (),
                                {"help_text": "Video"},
                            ),
                        },
                        help_text="Page content",
                        verbose_name="content",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
